#ifndef __AniDefs_h__
#define __AniDefs_h__

static const std::vector<std::string> g_aniNames = {
	"air_chuanqiu.ccbi",		//0
	"air_fengdu_failed.ccbi",		//1
	"air_fengdu_randomball.ccbi",		//2
	"air_fengdu_reduced.ccbi",		//3
	"air_fengdu_success.ccbi",		//4
	"air_jiewei.ccbi",		//5
	"air_keeper_chuji.ccbi",		//6
	"air_keeper_chuji_success.ccbi",		//7
	"air_lanjie_failed.ccbi",		//8
	"air_lanjie_randomball.ccbi",		//9
	"air_lanjie_reduced.ccbi",		//10
	"air_lanjie_success.ccbi",		//11
	"air_randomball_tingqiu.ccbi",		//12
	"air_shemen.ccbi",		//13
	"air_tiaoqi.ccbi",		//14
	"air_tingqiu.ccbi",		//15
	"air_zaoyu.ccbi",		//16
	"ball_air_lanjie.ccbi",		//17
	"ball_air_shemen.ccbi",		//18
	"ball_chujie.ccbi",		//19
	"ball_goal.ccbi",		//20
	"ball_goal_critical.ccbi",		//21
	"ball_ground_lanjie.ccbi",		//22
	"ball_ground_shemen.ccbi",		//23
	"ball_halfair_shemen.ccbi",		//24
	"ball_menkuang.ccbi",		//25
	"ball_random.ccbi",		//26
	"bianxianqiu.ccbi",		//27
	"bufang_failed.ccbi",		//28
	"bufang_success.ccbi",		//29
	"duikang.ccbi",		//30
	"ground_2guo1.ccbi",		//31
	"ground_chanqiu_failed.ccbi",		//32
	"ground_chanqiu_randomball.ccbi",		//33
	"ground_chanqiu_reduced.ccbi",		//34
	"ground_chanqiu_success.ccbi",		//35
	"ground_chuanqiu.ccbi",		//36
	"ground_daiqiu.ccbi",		//37
	"ground_fengdu_failed.ccbi",		//38
	"ground_fengdu_paowei.ccbi",		//39
	"ground_fengdu_randomball.ccbi",		//40
	"ground_fengdu_reduced.ccbi",		//41
	"ground_fengdu_success.ccbi",		//42
	"ground_jiewei.ccbi",		//43
	"ground_keeper_anti_daiqiu.ccbi",		//44
	"ground_keeper_anti_shemen.ccbi",		//45
	"ground_keeper_anti_shemen_failed.ccbi",		//46
	"ground_keeper_chuji.ccbi",		//47
	"ground_keeper_chuji_success.ccbi",		//48
	"ground_lanjie_failed.ccbi",		//49
	"ground_lanjie_paowei.ccbi",		//50
	"ground_lanjie_randomball.ccbi",		//51
	"ground_lanjie_reduced.ccbi",		//52
	"ground_lanjie_success.ccbi",		//53
	"ground_pandai.ccbi",		//54
	"ground_paowei.ccbi",		//55
	"ground_randomball_tingqiu.ccbi",		//56
	"ground_shemen.ccbi",		//57
	"ground_tingqiu.ccbi",		//58
	"ground_zaoyu.ccbi",		//59
	"halfair_shemen.ccbi",		//60
	"jiaoqiu_chuanqiu.ccbi",		//61
	"jiaoqiu_shemen.ccbi",		//62
	"judgment_break.ccbi",		//63
	"judgment_over.ccbi",		//64
	"judgment_start.ccbi",		//65
	"keeper_jiqiu_failed.ccbi",		//66
	"keeper_jiqiu_randomball.ccbi",		//67
	"keeper_jiqiu_success.ccbi",		//68
	"keeper_woqiu_failed.ccbi",		//69
	"keeper_woqiu_randomball.ccbi",		//70
	"keeper_woqiu_success.ccbi",		//71
	"penaltykick.ccbi",		//72
};

#endif // __AniDefs_h__
